var
  lang := [('Азербайджанский', 'Salaam aleihum'),
  ('Албанский', 'Tungjatjeta'),
  ('Английский', 'Hello'),
  ('Арабский', 'Ahlan wa sahlan'),
  ('Арабский', 'Ahlen'),
  ('Арабский', 'Marhaba'),
  ('Армянский', 'Voghdzuyin'),
  ('Ассирийский', 'Shlama'),
  ('Африкаанс', 'Goeie dag'),
  ('Башкирский', 'Kheyerle'),
  ('Белорусский', 'Pryvitani'),
  ('Бенгальский', 'Nomoskaar'),
  ('Болгарский', 'Zdraveite'),
  ('Боснийский', 'Zdravo'),
  ('Венгерский', 'Jo napot'),
  ('Вьетнамский', 'Chao'),
  ('Гавайский', 'Aloha'),
  ('Гагаузский', 'Gun aydin'),
  ('Голландский', 'Hallo'),
  ('Греческий', 'Geia sou'),
  ('Грузинский', 'Gamardjobat'),
  ('Датский', 'God dag'),
  ('Еврейский', 'Shalom'),
  ('Египетский', 'Iiti'),
  ('Зулу', 'Sawubona'),
  ('Ингушский', 'Salam'),
  ('Индонезийский', 'Selamat'),
  ('Исландский', 'Godan'),
  ('Испанский', 'Buenos'),
  ('Итальянский', 'Buon'),
  ('Казахский', 'Salam'),
  ('Киргизский', 'Salaam'),
  ('Калмыки', 'Mendvt'),
  ('Каракалпакский', 'Assalomu alaikum'),
  ('Кирибати', 'Mauri'),
  ('Команче', 'Haa'),
  ('Корейский', 'Annyoung hasimnikka'),
  ('Коряки', 'Mej'),
  ('Кхмеры', 'Sok sabai'),
  ('Латинский', 'Ave Vale'),
  ('Латышский', 'Sveiki'),
  ('Литовский', 'Sveikas'),
  ('Люксембург', 'Moien'),
  ('Македония', 'Zdravo'),
  ('Мордовский', 'Shumbrat'),
  ('Ндебеле', 'Sawubona'),
  ('Немецкий', 'Guten'),
  ('Норвежский', 'Goddag'),
  ('Польский', 'Dzien dobry'),
  ('Португальский', 'Ola'),
  ('Прусский', 'Kails'),
  ('Румынский', 'Buna'),
  ('Русский', 'Zdravstvuite'),
  ('Сербский', 'Zdravo'),
  ('Сицилия', 'Sa' + Chr(10) + 'benerica'),
  ('Словацкий', 'Dobry den'),
  ('Тайский', 'Sawatdi'),
  ('Татарский', 'Isenmesez'),
  ('Тибет', 'Kam'),
  ('Турецкий', 'Merhaba'),
  ('Удмурты', 'Ziech'),
  ('Узбекский', 'Salaam aleikhem'),
  ('Украинский', 'Pryvit'),
  ('Уэльский', 'Dydd da'),
  ('Финский', 'Paivaa'),
  ('Французский', 'Bonjour '),
  ('Хинди', 'Namaste'),
  ('Хорватский', 'Zdravo'),
  ('Чеченский', 'Marsha voghiila'),
  ('Чешский', 'Dobry den'),
  ('Чувашский', 'Salam'),
  ('Чукчи', 'Ye' + Chr(10) + 'ti'),
  ('Шведский', 'God dag'),
  ('Шотландский', 'Guid mornin'),
  ('Эсперанто', 'Saluton'),
  ('Эстонский', 'Tervist'),
  ('Японский', 'Konnichi wa')];


begin
  var input := ReadString('На каком языке вы говорите?'+Chr(10)+'Введите язык:').ToLower;
  
  foreach var pair in lang do
    if input in pair.Item1.ToLower then // англ = английский
    begin
      Print(pair.Item2);
      exit;
    end;
  
  Print('Я не знаю такой язык');
end.